### ISSUE TITLE
Place predictions after event has started/finished

### ISSUE THREAD

**Issue by rfoel** [samternent/home#324]
I was able to call the API from the console and make the correct prediction for a game that had already finished.

<img width="904" alt="image" src="https://github.com/samternent/home/assets/19496473/c764dd05-ba50-4bcc-9f34-71e885d26d99">

<img width="899" alt="image" src="https://github.com/samternent/home/assets/19496473/9eab2dd5-3bba-4541-b2d1-faa451bc48b1">

**Comment by samternent** [comment]
Thank you for reporting this @rfoel .

It'll take me a little while to get a fix in place for it as I'll need to implement a new dedicated endpoint.
Could you please hold off adding any further predictions this way 🙏🏻  Once a fix is in place I'll go through and clear out any data that was added outside of the rules.
